name: Deploy to Netlify with PR and Email Notification

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

\
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the app
      - name: Build the app
        run: npm run build --verbose

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: ${{ github.ref == 'refs/heads/prod' }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Step 6: Create a Pull Request (if deploying to production)
      - name: Create Pull Request
        if: github.ref_name == 'dev'
        run: |
          git fetch origin
          git checkout -b prod || git checkout prod
          git merge dev --no-edit
          git push origin prod
          echo "Pull request has been created between dev and prod branches."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  send-email-notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      # Step 1: Send email notification
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Netlify Deployment Notification"
          body: |
            Hello Team,

            The application has been successfully deployed to Netlify.

            Branch: ${{ github.ref_name }}
            Site URL: https://your-netlify-site.netlify.app

            Regards,
            Deployment Bot
          to: mgorle@anergroup.com
          from: mgorle@anergroup.com
