name: Multi-Environment Deployment with Auto-Merge to Prod
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
 
      # Step 4: Run tests (only for test branch)
      - name: Run tests
        if: github.ref_name == 'dev'
        run: npm test
 
      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose
      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh /build || echo "Dist directory not found"
      # Step 7: Deploy to Netlify (Test branch)
      - name: Deploy to Netlify (dev)
        if: github.ref == 'refs/heads/dev'  # Deploy on test branch
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: false  # Ensure this deploy is not to production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TEST_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.HOMEPAGE_URL }}  # Use the test homepage URL from secrets
  auto-merge-to-prod:
    name: Auto-Merge to Prod
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: success() && github.ref == 'refs/heads/dev'  # Trigger auto-merge only after test branch success
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Step 2: Configure Git User
      - name: Configure Git User
        run: |
          git config --global user.name "manasagorle-2698q"
          git config --global user.email "mgorle@anergroup.com"
      # Step 3: Merge Test into Prod with Automatic Conflict Resolution
      - name: Merge Test into Prod
        run: |
          git fetch origin
          git checkout prod
          git merge dev --strategy-option theirs --allow-unrelated-histories --no-edit
          git push origin prod
  deploy-to-netlify-prod:
    name: Deploy to Netlify (Prod)
    runs-on: ubuntu-latest
    needs: auto-merge-to-prod
    if: success()  # Deploy only after auto-merge to prod succeeds
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
     
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
 
      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose
 
      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh /dist || echo "Dist directory not found"
 
      # Step 2: Deploy to Netlify (Prod)
      - name: Deploy to Netlify (Prod)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: true  # This deploys to production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.PROD_HOMEPAGE_URL }}  # Use the prod homepage URL from secrets